### ISSUE TITLE
non-programmer, don't understand 

### ISSUE THREAD

**Issue by j2l** [mmaldacker/Vortex2D#18] opened 2019-03-05 10:09 UTC
I tried to follow up how to build it but don't get anything usable.
Could a C++ guru can point me in the right direction?
So far I have:
![image](https://user-images.githubusercontent.com/65325/53797737-13d52e00-3f37-11e9-9b91-96724587f400.png)

Then, In code::blocks, I build and get:
```
||=== Build: all in Vortex2D (compiler: GNU GCC Compiler) ===|
E:\Downloads\Vortex2D-1.5.0\Vortex2D\Utils\vk_mem_alloc.h||In function 'void* VmaMalloc(const VkAllocationCallbacks*, size_t, size_t)':|
E:\Downloads\Vortex2D-1.5.0\Vortex2D\Utils\vk_mem_alloc.h|2283|error: '_aligned_malloc' was not declared in this scope|
E:\Downloads\Vortex2D-1.5.0\Vortex2D\Utils\vk_mem_alloc.h|2658|note: in expansion of macro 'VMA_SYSTEM_ALIGNED_MALLOC'|
E:\Downloads\Vortex2D-1.5.0\Vortex2D\Utils\vk_mem_alloc.h||In function 'void VmaFree(const VkAllocationCallbacks*, void*)':|
E:\Downloads\Vortex2D-1.5.0\Vortex2D\Utils\vk_mem_alloc.h|2291|error: '_aligned_free' was not declared in this scope|
E:\Downloads\Vortex2D-1.5.0\Vortex2D\Utils\vk_mem_alloc.h|2671|note: in expansion of macro 'VMA_SYSTEM_FREE'|
Vortex2D\CMakeFiles\vortex2d.dir\build.make|458|recipe for target 'Vortex2D/CMakeFiles/vortex2d.dir/Renderer/Device.cpp.obj' failed|
CMakeFiles\Makefile2|94|recipe for target 'Vortex2D/CMakeFiles/vortex2d.dir/all' failed|
E:\Downloads\Vortex2D-1.5.0\build\Makefile|128|recipe for target 'all' failed|
||=== Build failed: 5 error(s), 0 warning(s) (1 minute(s), 39 second(s)) ===|

```
What is wrong?

Thanks

**Comment by mmaldacker** [comment] 2019-03-05 18:14
Hi, 

Do you know which version of mingw/gcc you are using?

I haven't tried to make the project compile with mingw. I just tried with the latest version of mingw-64 (x86_64-8.1.0-posix-seh). Found some issues (but not the one you're having), which I've fixed and committed. 

Alternatively, you can always download the latest version of visual studio community, which is free.

Max

**Comment by j2l** [comment] 2019-03-05 19:33
I downloaded Code::Block for this. It's 17.12, but I don't know about MiniGW version.
I hate Visual Studio, that's why I avoided it after I re-install Windows.
If you tried with MIniGW, could you please add the link to it and tell me if your fixes are already published? So I could build it with Code::Block.

**Comment by mmaldacker** [comment] 2019-03-07 21:16
Ok. The default version of mingw coming with Code::Block 17.12 is 5.1 which is a bit outdated. You need at least 5.4. Note that you'll have to use the master version of Vortex2D and not 1.5, as I've had to fix other issues with mingw on windows.

I've also added precompiled windows binaries to the 1.5 release, in case all you wanted to do was to run the examples (use numbers 1 till 8 to run the different scenes).

**Comment by j2l** [comment] 2019-03-08 08:50
Thank you very much for going the extra mile by proving a precompiled version of examples.
Not sure if related but I get an error on vortex2d_example:
```
Device name: GeForce GTX 970
validation layer:  [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass ] Object: VK_NULL_HANDLE (Type = 0) | Render pass has an attachment with loadOp == VK_ATTACHMENT_LOAD_OP_LOAD and initialLayout == VK_IMAGE_LAYOUT_UNDEFINED.  This is probably not what you intended.  Consider using VK_ATTACHMENT_LOAD_OP_DONT_CARE instead if the image truely is undefined at the start of the render pass.
```
and here's vortex2d_tests.exe results:
```
Device name: GeForce GTX 970
[==========] Running 92 tests from 15 test suites.
[----------] Global test environment set-up.
[----------] 5 tests from AdvectionTests
[ RUN      ] AdvectionTests.AdvectVelocity_Simple
[       OK ] AdvectionTests.AdvectVelocity_Simple (289 ms)
[ RUN      ] AdvectionTests.AdvectVelocity_Complex
[       OK ] AdvectionTests.AdvectVelocity_Complex (208 ms)
[ RUN      ] AdvectionTests.Advect
[       OK ] AdvectionTests.Advect (199 ms)
[ RUN      ] AdvectionTests.ParticleAdvect
[       OK ] AdvectionTests.ParticleAdvect (202 ms)
[ RUN      ] AdvectionTests.ParticleProject
[       OK ] AdvectionTests.ParticleProject (195 ms)
[----------] 5 tests from AdvectionTests (1100 ms total)

[----------] 4 tests from BoundariesTests
[ RUN      ] BoundariesTests.Square
[       OK ] BoundariesTests.Square (16 ms)
[ RUN      ] BoundariesTests.InverseSquare
[       OK ] BoundariesTests.InverseSquare (14 ms)
[ RUN      ] BoundariesTests.Circle
[       OK ] BoundariesTests.Circle (11 ms)
[ RUN      ] BoundariesTests.Intersection
[       OK ] BoundariesTests.Intersection (14 ms)
[----------] 4 tests from BoundariesTests (58 ms total)

[----------] 1 test from BoundariesTest
[ RUN      ] BoundariesTest.DistanceField
[       OK ] BoundariesTest.DistanceField (16 ms)
[----------] 1 test from BoundariesTest (17 ms total)

[----------] 2 tests from ExtrapolateTest
[ RUN      ] ExtrapolateTest.Extrapolate
[       OK ] ExtrapolateTest.Extrapolate (27 ms)
[ RUN      ] ExtrapolateTest.Constrain
[       OK ] ExtrapolateTest.Constrain (30 ms)
[----------] 2 tests from ExtrapolateTest (60 ms total)

[----------] 3 tests from LevelSetTests
[ RUN      ] LevelSetTests.SimpleCircle
[       OK ] LevelSetTests.SimpleCircle (23 ms)
[ RUN      ] LevelSetTests.ComplexCircles
[       OK ] LevelSetTests.ComplexCircles (24 ms)
[ RUN      ] LevelSetTests.Extrapolate
[       OK ] LevelSetTests.Extrapolate (13 ms)
[----------] 3 tests from LevelSetTests (65 ms total)

[----------] 13 tests from LinearSolverTests
[ RUN      ] LinearSolverTests.ReduceSum
[       OK ] LinearSolverTests.ReduceSum (6 ms)
[ RUN      ] LinearSolverTests.ReduceBigSum
[       OK ] LinearSolverTests.ReduceBigSum (3 ms)
[ RUN      ] LinearSolverTests.ReduceMax
[       OK ] LinearSolverTests.ReduceMax (6 ms)
[ RUN      ] LinearSolverTests.Transfer_Prolongate
[       OK ] LinearSolverTests.Transfer_Prolongate (13 ms)
[ RUN      ] LinearSolverTests.Transfer_Restrict
[       OK ] LinearSolverTests.Transfer_Restrict (14 ms)
[ RUN      ] LinearSolverTests.Simple_SOR
Solved with number of iterations: 87
[       OK ] LinearSolverTests.Simple_SOR (33 ms)
[ RUN      ] LinearSolverTests.Complex_SOR
Solved with number of iterations: 129
[       OK ] LinearSolverTests.Complex_SOR (35 ms)
[ RUN      ] LinearSolverTests.LocalGaussSeidel
[       OK ] LinearSolverTests.LocalGaussSeidel (13 ms)
[ RUN      ] LinearSolverTests.Diagonal_Simple_PCG
Solved with number of iterations: 92
[       OK ] LinearSolverTests.Diagonal_Simple_PCG (47 ms)
[ RUN      ] LinearSolverTests.GaussSeidel_Simple_PCG
Solved with number of iterations: 21
[       OK ] LinearSolverTests.GaussSeidel_Simple_PCG (47 ms)
[ RUN      ] LinearSolverTests.IncompletePoisson_Simple_PCG
Solved with number of iterations: 56
[       OK ] LinearSolverTests.IncompletePoisson_Simple_PCG (48 ms)
[ RUN      ] LinearSolverTests.Zero_PCG
[       OK ] LinearSolverTests.Zero_PCG (29 ms)
[ RUN      ] LinearSolverTests.Multigrid_Simple_PCG
Solved with number of iterations: 16
[       OK ] LinearSolverTests.Multigrid_Simple_PCG (170 ms)
[----------] 13 tests from LinearSolverTests (483 ms total)

[----------] 12 tests from ParticleTests
[ RUN      ] ParticleTests.PrefixScan
[       OK ] ParticleTests.PrefixScan (24 ms)
[ RUN      ] ParticleTests.PrefixScanBig
[       OK ] ParticleTests.PrefixScanBig (3 ms)
[ RUN      ] ParticleTests.ParticleCounting
[       OK ] ParticleTests.ParticleCounting (74 ms)
[ RUN      ] ParticleTests.ParticleCounting_OffBounds
[       OK ] ParticleTests.ParticleCounting_OffBounds (35 ms)
[ RUN      ] ParticleTests.ParticleDelete
[       OK ] ParticleTests.ParticleDelete (37 ms)
[ RUN      ] ParticleTests.ParticleClamp
[       OK ] ParticleTests.ParticleClamp (32 ms)
[ RUN      ] ParticleTests.ParticleSpawn
[       OK ] ParticleTests.ParticleSpawn (27 ms)
[ RUN      ] ParticleTests.ParticleAddDelete
[       OK ] ParticleTests.ParticleAddDelete (39 ms)
[ RUN      ] ParticleTests.Phi
[       OK ] ParticleTests.Phi (42 ms)
[ RUN      ] ParticleTests.FromGrid_PIC
[       OK ] ParticleTests.FromGrid_PIC (43 ms)
[ RUN      ] ParticleTests.FromGrid_FLIP
[       OK ] ParticleTests.FromGrid_FLIP (43 ms)
[ RUN      ] ParticleTests.ToGrid
[       OK ] ParticleTests.ToGrid (50 ms)
[----------] 12 tests from ParticleTests (473 ms total)

[----------] 5 tests from PressureTest
[ RUN      ] PressureTest.LinearEquationSetup_Simple
[       OK ] PressureTest.LinearEquationSetup_Simple (46 ms)
[ RUN      ] PressureTest.LinearEquationSetup_Complex
[       OK ] PressureTest.LinearEquationSetup_Complex (46 ms)
[ RUN      ] PressureTest.ZeroDivs
[       OK ] PressureTest.ZeroDivs (43 ms)
[ RUN      ] PressureTest.Project_Simple
[       OK ] PressureTest.Project_Simple (35 ms)
[ RUN      ] PressureTest.Project_Complex
[       OK ] PressureTest.Project_Complex (44 ms)
[----------] 5 tests from PressureTest (223 ms total)

[----------] 12 tests from RigidbodyTests
[ RUN      ] RigidbodyTests.Phi
[       OK ] RigidbodyTests.Phi (50 ms)
[ RUN      ] RigidbodyTests.Div
[       OK ] RigidbodyTests.Div (96 ms)
[ RUN      ] RigidbodyTests.VelocityDiv
[       OK ] RigidbodyTests.VelocityDiv (92 ms)
[ RUN      ] RigidbodyTests.RotationDiv
[       OK ] RigidbodyTests.RotationDiv (86 ms)
[ RUN      ] RigidbodyTests.VelocityRotationDiv
[       OK ] RigidbodyTests.VelocityRotationDiv (94 ms)
[ RUN      ] RigidbodyTests.ReduceJSum
[       OK ] RigidbodyTests.ReduceJSum (1 ms)
[ RUN      ] RigidbodyTests.Force
[       OK ] RigidbodyTests.Force (62 ms)
[ RUN      ] RigidbodyTests.Pressure
[       OK ] RigidbodyTests.Pressure (88 ms)
[ RUN      ] RigidbodyTests.PressureVelocity
Solved in 266 iterations. Error 4.40862e-05
[       OK ] RigidbodyTests.PressureVelocity (137 ms)
[ RUN      ] RigidbodyTests.PressureRotation
Solved in 201 iterations. Error 5.90863e-06
[       OK ] RigidbodyTests.PressureRotation (123 ms)
[ RUN      ] RigidbodyTests.VelocityConstrain
[       OK ] RigidbodyTests.VelocityConstrain (50 ms)
[ RUN      ] RigidbodyTests.RotationConstrain
[       OK ] RigidbodyTests.RotationConstrain (42 ms)
[----------] 12 tests from RigidbodyTests (937 ms total)

[----------] 3 tests from WorldTests
[ RUN      ] WorldTests.PressureRigidbody_Velocity
Scale 2 Mass 512 Scaled Force (7047.23)
Scale 4 Mass 32 Scaled Force (7055.31)
Scale 8 Mass 2 Scaled Force (7042.02)
Scale 16 Mass 0.125 Scaled Force (6937.79)
Std deviation: 48.0398
[       OK ] WorldTests.PressureRigidbody_Velocity (2218 ms)
[ RUN      ] WorldTests.PressureRigidbody_Rotation
Scale 2 Inertia 177493 Scaled Torque (35.3561)
..\Tests\Engine\WorldTests.cpp(143): error: The difference between forces.velocity.x / (mass * scale) and 0.0f is 0.011547088623046875, which exceeds 1e-2f, where
forces.velocity.x / (mass * scale) evaluates to -0.011547088623046875,
0.0f evaluates to 0, and
1e-2f evaluates to 0.0099999997764825821.
Scale 4 Inertia 693.333 Scaled Torque (35.6338)
Scale 8 Inertia 2.70833 Scaled Torque (35.9677)
Scale 16 Inertia 0.0105794 Scaled Torque (36.1146)
Std deviation: 0.294839
[  FAILED  ] WorldTests.PressureRigidbody_Rotation (2463 ms)
[ RUN      ] WorldTests.Velocity
[       OK ] WorldTests.Velocity (522 ms)
[----------] 3 tests from WorldTests (5204 ms total)

[----------] 1 test from CflTets
[ RUN      ] CflTets.Max
[       OK ] CflTets.Max (15 ms)
[----------] 1 test from CflTets (17 ms total)

[----------] 12 tests from ComputeTests
[ RUN      ] ComputeTests.WriteBuffer
[       OK ] ComputeTests.WriteBuffer (0 ms)
[ RUN      ] ComputeTests.BufferCopy
[       OK ] ComputeTests.BufferCopy (2 ms)
[ RUN      ] ComputeTests.UpdateVectorBuffer
[       OK ] ComputeTests.UpdateVectorBuffer (0 ms)
[ RUN      ] ComputeTests.BufferCompute
[       OK ] ComputeTests.BufferCompute (2 ms)
[ RUN      ] ComputeTests.ImageCompute
[       OK ] ComputeTests.ImageCompute (6 ms)
[ RUN      ] ComputeTests.Work
[       OK ] ComputeTests.Work (9 ms)
[ RUN      ] ComputeTests.WorkIndirect
[       OK ] ComputeTests.WorkIndirect (5 ms)
[ RUN      ] ComputeTests.FloatImage
[       OK ] ComputeTests.FloatImage (7 ms)
[ RUN      ] ComputeTests.Stencil
[       OK ] ComputeTests.Stencil (7 ms)
[ RUN      ] ComputeTests.Checkerboard
[       OK ] ComputeTests.Checkerboard (10 ms)
[ RUN      ] ComputeTests.Timer
Elapsed time: 190432
[       OK ] ComputeTests.Timer (5 ms)
[ RUN      ] ComputeTests.Reflection
[       OK ] ComputeTests.Reflection (0 ms)
[----------] 12 tests from ComputeTests (77 ms total)

[----------] 10 tests from RenderingTest
[ RUN      ] RenderingTest.WriteHostTextureInt
[       OK ] RenderingTest.WriteHostTextureInt (1 ms)
[ RUN      ] RenderingTest.WriteHostTextureFloat
[       OK ] RenderingTest.WriteHostTextureFloat (0 ms)
[ RUN      ] RenderingTest.TextureCopy
[       OK ] RenderingTest.TextureCopy (3 ms)
[ RUN      ] RenderingTest.TextureBufferCopy
[       OK ] RenderingTest.TextureBufferCopy (1 ms)
[ RUN      ] RenderingTest.ClearTexture
[       OK ] RenderingTest.ClearTexture (11 ms)
[ RUN      ] RenderingTest.IntClearTexture
[       OK ] RenderingTest.IntClearTexture (6 ms)
[ RUN      ] RenderingTest.BlendAdd
[       OK ] RenderingTest.BlendAdd (8 ms)
[ RUN      ] RenderingTest.MoveCommandBuffer
[       OK ] RenderingTest.MoveCommandBuffer (9 ms)
[ RUN      ] RenderingTest.CommandBufferWait
[       OK ] RenderingTest.CommandBufferWait (3 ms)
[ RUN      ] RenderingTest.Sprite
[       OK ] RenderingTest.Sprite (8 ms)
[----------] 10 tests from RenderingTest (64 ms total)

[----------] 8 tests from ShapeTests
[ RUN      ] ShapeTests.Square
[       OK ] ShapeTests.Square (6 ms)
[ RUN      ] ShapeTests.IntSquare
[       OK ] ShapeTests.IntSquare (14 ms)
[ RUN      ] ShapeTests.MultipleSquares
[       OK ] ShapeTests.MultipleSquares (10 ms)
[ RUN      ] ShapeTests.Circle
[       OK ] ShapeTests.Circle (6 ms)
[ RUN      ] ShapeTests.Ellipse
[       OK ] ShapeTests.Ellipse (11 ms)
[ RUN      ] ShapeTests.ScaledEllipse
[       OK ] ShapeTests.ScaledEllipse (7 ms)
[ RUN      ] ShapeTests.RotatedEllipse
[       OK ] ShapeTests.RotatedEllipse (10 ms)
[ RUN      ] ShapeTests.RenderScaledEllipse
[       OK ] ShapeTests.RenderScaledEllipse (6 ms)
[----------] 8 tests from ShapeTests (78 ms total)

[----------] 1 test from Vulkan
[ RUN      ] Vulkan.Init
Device name: GeForce GTX 970
Max local size 0 : 1536
Max local size 1 : 1024
Max local size 2 : 64
Max local size total: 1536
[       OK ] Vulkan.Init (7 ms)
[----------] 1 test from Vulkan (9 ms total)

[----------] Global test environment tear-down
[==========] 92 tests from 15 test suites ran. (8890 ms total)
[  PASSED  ] 91 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] WorldTests.PressureRigidbody_Rotation

 1 FAILED TEST
```

**Comment by mmaldacker** [comment] 2019-03-13 19:23
Hi, thanks for your feedback!

For the first issue, it's been on my todo list for a while, just fixed it. 

For the second one, it's a test that runs a single step of the simulation with all the bells and whistles.  The issue is everything is done with single-precision floating point when the simulation should be done with double-precision floating point. However consumer GPU cards have very poor performance, so I have to live with some imprecision with single-precision floating point. I'll reduce the error tolerance.

If you have time/don't mind, could you tell me the value one the title bar when running vortex2d_example, with each scene (1 through 8)? This is the time a single frame takes to compute/render and I'd be interested to see how it performs with a GTX970.

Thanks!

**Comment by j2l** [comment] 2019-03-13 19:50
Hi,
Thanks.
Sure, 32ms and it's a black screen, no scene at all.

**Comment by mmaldacker** [comment] 2019-03-13 20:22
Black screen? And if you press the key "5"?

**Comment by j2l** [comment] 2019-03-13 20:25
OK, they works.
But numbers are not default on AZERTY keyboards.

**Closed as completed** 2019-04-04 18:59 UTC
Labels: question
